export const BLOCK_TYPES = {
  EMPTY: 0,
  GRASS: 1,
  DIRT: 2,
  STONE: 3,
  REDSTONE: 4,
  IRON: 5,
  GOLD: 6,
  EMERALD: 7,
  NETHERITE: 8,
  LOG: 9,
  LEAVES: 10,
  WATER: 11,
  MEAT: 12,
  DIAMOND_ORE: 13,
  WOOD_SWORD: 14,
  STONE_SWORD: 15,
  IRON_SWORD: 16,
  DIAMOND_SWORD: 17,
  SAND: 18,
  GLASS: 19,
  COBBLESTONE: 20,
  BRICK: 21,
  WOOD_PICKAXE: 22,
  STONE_PICKAXE: 23,
  IRON_PICKAXE: 24,
  DIAMOND_PICKAXE: 25,
  WOOD_AXE: 26,
  STONE_AXE: 27,
  IRON_AXE: 28,
  DIAMOND_AXE: 29,
  WOOD_SHOVEL: 30,
  STONE_SHOVEL: 31,
  IRON_SHOVEL: 32,
  DIAMOND_SHOVEL: 33,
  APPLE: 34,
  BREAD: 35,
  TORCH: 36,
  DOOR: 37,
  STAIRS: 38,
};

export const BLOCK_DATA = {
  [BLOCK_TYPES.GRASS]: { color: 0x4caf50, name: '草方块', solid: true, texture: 'textures/stone_texture.png' },
  [BLOCK_TYPES.DIRT]: { color: 0x8b4513, name: '泥土', solid: true, texture: 'textures/stone_texture.png' },
  [BLOCK_TYPES.STONE]: { color: 0x808080, name: '石头', solid: true, texture: 'textures/stone_texture.png' },
  [BLOCK_TYPES.REDSTONE]: { color: 0xff0000, name: '红石', solid: true },
  [BLOCK_TYPES.IRON]: { color: 0xd3d3d3, name: '铁', solid: true },
  [BLOCK_TYPES.GOLD]: { color: 0xffd700, name: '金', solid: true },
  [BLOCK_TYPES.EMERALD]: { color: 0x50c878, name: '绿宝石', solid: true },
  [BLOCK_TYPES.NETHERITE]: { color: 0x3c3c3c, name: '下界合金', solid: true },
  [BLOCK_TYPES.LOG]: { color: 0x5d4037, name: '木头', solid: true, texture: 'textures/wood_texture.png' },
  [BLOCK_TYPES.LEAVES]: { color: 0x388e3c, name: '树叶', solid: true, transparent: true },
  [BLOCK_TYPES.WATER]: { color: 0x2196f3, name: '水', solid: false, transparent: true },
  [BLOCK_TYPES.MEAT]: { color: 0xffa07a, name: '肉', solid: false, isItem: true, edible: true, texture: 'textures/leather_texture.png' },
  [BLOCK_TYPES.DIAMOND_ORE]: { color: 0x00ffff, name: '钻石矿', solid: true },
  [BLOCK_TYPES.WOOD_SWORD]: { color: 0x8b4513, name: '木剑', isItem: true, damage: 3, texture: 'textures/wood_texture.png' },
  [BLOCK_TYPES.STONE_SWORD]: { color: 0x808080, name: '石剑', isItem: true, damage: 4, texture: 'textures/stone_texture.png' },
  [BLOCK_TYPES.IRON_SWORD]: { color: 0xd3d3d3, name: '铁剑', isItem: true, damage: 6 },
  [BLOCK_TYPES.DIAMOND_SWORD]: { color: 0x00ffff, name: '钻石剑', isItem: true, damage: 10 },
  [BLOCK_TYPES.SAND]: { color: 0xfff59d, name: '沙子', solid: true, texture: 'textures/stone_texture.png' },
  [BLOCK_TYPES.GLASS]: { color: 0xe3f2fd, name: '玻璃', solid: true, transparent: true },
  [BLOCK_TYPES.COBBLESTONE]: { color: 0x707070, name: '圆石', solid: true, texture: 'textures/stone_texture.png' },
  [BLOCK_TYPES.BRICK]: { color: 0xb71c1c, name: '砖块', solid: true, texture: 'textures/stone_texture.png' },
  [BLOCK_TYPES.WOOD_PICKAXE]: { color: 0x8b4513, name: '木镐', isItem: true, miningSpeed: 1, texture: 'textures/wood_texture.png' },
  [BLOCK_TYPES.STONE_PICKAXE]: { color: 0x808080, name: '石镐', isItem: true, miningSpeed: 2, texture: 'textures/stone_texture.png' },
  [BLOCK_TYPES.IRON_PICKAXE]: { color: 0xd3d3d3, name: '铁镐', isItem: true, miningSpeed: 3 },
  [BLOCK_TYPES.DIAMOND_PICKAXE]: { color: 0x00ffff, name: '钻石镐', isItem: true, miningSpeed: 5 },
  [BLOCK_TYPES.WOOD_AXE]: { color: 0x8b4513, name: '木斧', isItem: true, miningSpeed: 1.5, texture: 'textures/wood_texture.png' },
  [BLOCK_TYPES.STONE_AXE]: { color: 0x808080, name: '石斧', isItem: true, miningSpeed: 2.5, texture: 'textures/stone_texture.png' },
  [BLOCK_TYPES.IRON_AXE]: { color: 0xd3d3d3, name: '铁斧', isItem: true, miningSpeed: 3.5 },
  [BLOCK_TYPES.DIAMOND_AXE]: { color: 0x00ffff, name: '钻石斧', isItem: true, miningSpeed: 4.5 },
  [BLOCK_TYPES.WOOD_SHOVEL]: { color: 0x8b4513, name: '木铲', isItem: true, miningSpeed: 1.2, texture: 'textures/wood_texture.png' },
  [BLOCK_TYPES.STONE_SHOVEL]: { color: 0x808080, name: '石铲', isItem: true, miningSpeed: 2.2, texture: 'textures/stone_texture.png' },
  [BLOCK_TYPES.IRON_SHOVEL]: { color: 0xd3d3d3, name: '铁铲', isItem: true, miningSpeed: 3.2 },
  [BLOCK_TYPES.DIAMOND_SHOVEL]: { color: 0x00ffff, name: '钻石铲', isItem: true, miningSpeed: 4.2 },
  [BLOCK_TYPES.APPLE]: { color: 0xff0000, name: '苹果', solid: false, isItem: true, edible: true },
  [BLOCK_TYPES.BREAD]: { color: 0xf5deb3, name: '面包', solid: false, isItem: true, edible: true },
  [BLOCK_TYPES.TORCH]: { color: 0xffff00, name: '火把', solid: false, light: 15, transparent: true },
  [BLOCK_TYPES.DOOR]: { color: 0x8b4513, name: '门', solid: true, texture: 'textures/wood_texture.png' },
  [BLOCK_TYPES.STAIRS]: { color: 0x707070, name: '楼梯', solid: true, texture: 'textures/stone_texture.png' },
};

export const CRAFTING_RECIPES = [
  { result: BLOCK_TYPES.WOOD_SWORD, ingredients: { [BLOCK_TYPES.LOG]: 2 } },
  { result: BLOCK_TYPES.STONE_SWORD, ingredients: { [BLOCK_TYPES.STONE]: 2, [BLOCK_TYPES.LOG]: 1 } },
  { result: BLOCK_TYPES.IRON_SWORD, ingredients: { [BLOCK_TYPES.IRON]: 2, [BLOCK_TYPES.LOG]: 1 } },
  { result: BLOCK_TYPES.DIAMOND_SWORD, ingredients: { [BLOCK_TYPES.DIAMOND_ORE]: 2, [BLOCK_TYPES.LOG]: 1 } },
  { result: BLOCK_TYPES.WOOD_PICKAXE, ingredients: { [BLOCK_TYPES.LOG]: 3 } },
  { result: BLOCK_TYPES.STONE_PICKAXE, ingredients: { [BLOCK_TYPES.STONE]: 3, [BLOCK_TYPES.LOG]: 1 } },
  { result: BLOCK_TYPES.IRON_PICKAXE, ingredients: { [BLOCK_TYPES.IRON]: 3, [BLOCK_TYPES.LOG]: 1 } },
  { result: BLOCK_TYPES.DIAMOND_PICKAXE, ingredients: { [BLOCK_TYPES.DIAMOND_ORE]: 3, [BLOCK_TYPES.LOG]: 1 } },
  { result: BLOCK_TYPES.WOOD_AXE, ingredients: { [BLOCK_TYPES.LOG]: 3 } },
  { result: BLOCK_TYPES.STONE_AXE, ingredients: { [BLOCK_TYPES.STONE]: 3, [BLOCK_TYPES.LOG]: 1 } },
  { result: BLOCK_TYPES.IRON_AXE, ingredients: { [BLOCK_TYPES.IRON]: 3, [BLOCK_TYPES.LOG]: 1 } },
  { result: BLOCK_TYPES.DIAMOND_AXE, ingredients: { [BLOCK_TYPES.DIAMOND_ORE]: 3, [BLOCK_TYPES.LOG]: 1 } },
  { result: BLOCK_TYPES.WOOD_SHOVEL, ingredients: { [BLOCK_TYPES.LOG]: 2 } },
  { result: BLOCK_TYPES.STONE_SHOVEL, ingredients: { [BLOCK_TYPES.STONE]: 2, [BLOCK_TYPES.LOG]: 1 } },
  { result: BLOCK_TYPES.IRON_SHOVEL, ingredients: { [BLOCK_TYPES.IRON]: 2, [BLOCK_TYPES.LOG]: 1 } },
  { result: BLOCK_TYPES.DIAMOND_SHOVEL, ingredients: { [BLOCK_TYPES.DIAMOND_ORE]: 2, [BLOCK_TYPES.LOG]: 1 } },
  { result: BLOCK_TYPES.GLASS, ingredients: { [BLOCK_TYPES.STONE]: 2 } },
  { result: BLOCK_TYPES.COBBLESTONE, ingredients: { [BLOCK_TYPES.STONE]: 1 } },
  { result: BLOCK_TYPES.BRICK, ingredients: { [BLOCK_TYPES.COBBLESTONE]: 2 } },
  { result: BLOCK_TYPES.BREAD, ingredients: { [BLOCK_TYPES.WHEAT]: 3 } },
];

// 为了合成面包，我们需要添加小麦
BLOCK_TYPES.WHEAT = 39;
BLOCK_DATA[BLOCK_TYPES.WHEAT] = { color: 0x8bc34a, name: '小麦', solid: true };
